#!/usr/bin/env php
<?php

require getcwd().'/vendor/autoload.php';

use BladeBuilder\Commands\Build;
use BladeBuilder\Commands\Init;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Init(null, getcwd()));
$application->add(new Build(null, getcwd()));
$application->run();
